Add a deterministic random number generator
MyJobGlasses/time_turner pull request #2
Opened 2019-04-08 14:37 UTC by gbillig

2019-04-08 15:21 UTC, cyb- requested changes

2019-04-08 15:21 UTC, cyb- commented on lib/time_turner/generator.rb
> +    attr_reader :log
la configuration de classe se mets generalement en haut de la classe pour une meilleure lisibilité, qdtu commence a lire la classe, tu vois tt de suite ce que tu as a dispo pour coder avant de rentrer dans le code

2019-04-08 15:21 UTC, cyb- commented on lib/time_turner/generator.rb
> +  class Generator
je l'appelerai plus `Base`, par "convention", un `Generator` c'est un generateur qui va generer des fichiers (`rails g model user email:string ...`) qui se placent d'ailleurs dans un dossier `generators` dans ta lib,donc pour eviter la confusion il faudrait trouver un autre nom 😉

2019-04-08 15:21 UTC, cyb- commented on time_turner.gemspec
> +  spec.add_dependency "activesupport", "~> 5"
vraiment besoin de ca ? je n'ai pas vu où 😕

2019-04-08 15:28 UTC, Startouf submitted a review, later dismissed

2019-04-08 15:28 UTC, Startouf commented on lib/time_turner/generator.rb
> +  class Generator
bah en même temps c'est bien un générateur ce qu'on est en train de faire.
Maintenant si on veut aller dans de l'exotique, on pourrait appeller ça `Hourglass` ou qqchose dans ce genre pour rester dans l'univers HP mais Generator j'aimais bien :S

2019-04-08 15:28 UTC, Startouf commented on lib/time_turner/generator.rb
> +    def initialize(seed)
Pas oublier de générer la doc, ici pas évident de vomprendre ce qu'est la seed. En plus de préciser que c'est une String, on pourra proposer un exemple en doc de comment la générer (`SecureRandom.hex(24)` ?)

2019-04-08 15:28 UTC, Startouf commented on lib/time_turner/generator.rb
> +      @rng = Random.new(seed)
```suggestion
      @rng = Random.new(seed)
```
Il faut éviter de tronquer les noms de variables comme ça. Perso j'arrive même pas à voir ce que rng signifie. j'aurais dit `range` mais ça me semble pas être le cas. Juste `@random` aurait suffi ici par exemple

2019-04-08 15:28 UTC, Startouf commented on time_turner.gemspec
> +  spec.add_dependency "activesupport", "~> 5"
Oui si on peut enlever AS les gens seront hyper contents. Maintenant je crois qu'à terme on sera obligé de l'utiliser.

2019-04-08 16:23 UTC, gbillig commented on time_turner.gemspec
> +  spec.add_dependency "activesupport", "~> 5"
Avec les prochaines fonctionnalités, on en aura besoin.

2019-04-08 16:29 UTC, gbillig commented on lib/time_turner/generator.rb
> +    def initialize(seed)
En fait c'est un `Integer` ^^
Je pense qu'il suffit d'indiquer que c'est un `Integer`, pas besoin d'example parce que tout les `Integer`s sont valides.

2019-04-08 16:31 UTC, gbillig commented on time_turner.gemspec
> +  spec.add_dependency "activesupport", "~> 5"
Ah si je l'utilise dans les specs: `1.month.ago`.

2019-04-08 16:53 UTC, Startouf approved these changes

2019-04-09 08:10 UTC, merged

2019-04-09 12:46 UTC, cyb- commented on lib/time_turner/generator.rb
> +  class Generator
par CONVENTION, un `Generator` dans rails c'est un generateur de fichier...